config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :charges, only: [:new, :create]

  resources :wikiis do
    resources :collaborators, only: [:create, :destroy]
  end

  resources :users, only: [:show] do
    member do
      get 'downgrade'
    end
  end

  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wikii
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:standard, :premium, :admin]
  after_initialize :set_default_role, :if => :new_record?

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  has_many :wikiis, dependent: :destroy
  has_many :collaborators
  has_many :wiki_collabs, source: 'wiki', through: :collaborators

  def set_default_role
    self.role ||= :standard
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/models/wikii.rb
class Wikii < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    # Amount in cents
    @amount = 1500

    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Wiki Premium - #{current_user.username}",
      amount: @amount
    }
  end

  def create
    # Amount in cents
    @amount = 1500

    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: @amount,
      description: "Wiki Premium - #{current_user.email}",
      currency: 'usd'
    )

    current_user.premium!

    flash[:notice] = "Thanks for upgrading, #{current_user.username}!"
    redirect_to wikiis_path

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @wikii = Wikii.find(params[:wikii_id])
    @user = User.find_by_email(params[:collaborator][:user])

    if User.exists?(@user.id)
      @collaborator = @wikii.collaborators.new(wikii_id: @wikii.id, user_id: @user.id)

      if @collaborator.save
        flash[:notice] = "User added"
      else
        flash[:error] = "Error"
      end
      redirect_to @wikii
    else
      flash[:error] = "Error, no such user"
      redirect_to @wikii
    end
  end

  def destroy
    @wikii = Wikii.find(params[:wikii_id])
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Delete successfull"
      redirect_to @wikii
    else
      flash.now[:alert] = "There was an error"
      redirect_to @wikii
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @wikiis = policy_scope(Wikii)
  end

  def downgrade
    current_user.standard!
    current_user.wikiis.each do |wikii|
      if wikii.private?
        wikii.update :private => false
      end
    end
    flash[:notice] = "Your account has been downgraded back to standard."
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikiis_controller.rb
class WikiisController < ApplicationController
  include Pundit
  protect_from_forgery

  def index
    @wikiis = policy_scope(Wikii.all)
  end

  def show
    @wikii = Wikii.find(params[:id])
    @collaborators = @wikii.collaborators
  end

  def new
    @wikii = Wikii.new
  end

  def create
    @wikii = Wikii.new
    @wikii.title = params[:wikii][:title]
    @wikii.body = params[:wikii][:body]
    @wikii.private = params[:wikii][:private]
    @wikii.user = current_user

    if @wikii.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wikii
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wikii = Wikii.find(params[:id])
    @collaborators = @wikii.collaborators
  end

  def update
    @wikii = Wikii.find(params[:id])
    authorize @wikii
    @wikii.title = params[:wikii][:title]
    @wikii.body = params[:wikii][:body]
    @wikii.private = params[:wikii][:private]

    if @wikii.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wikii
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wikii = Wikii.find(params[:id])
    authorize @wikii

    if @wikii.destroy
      flash[:notice] = "\"#{@wikii.title}\" was deleted successfully."
      redirect_to wikiis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page_style(controller, action)
    'active' if current_page?(controller: controller, action: action)
  end

  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikiis_helper.rb
module WikiisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/_form.html.erb
<% if @wikii.private %>
  <%= form_for [wikii, Collaborator.new] do |f| %>
    Add Collaborators using their email address
     <%= f.text_field :user, placeholder: "User email address" %>

     <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/collaborators/_list.html.erb
<h3>Collaborators:</h3>
<% @wikii.collaborators.each do |collaborator| %>
  <p>
    <%= User.find_by_id(collaborator.user_id).username %>
    <% if policy(@wikii).destroy? %>
     - <%= link_to "Remove", [@wikii, collaborator], method: :delete, data: {confirm: 'Are you sure you want to delete this collaborator?'} %>
    <% end %>
  </p>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiki</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Oleo+Script" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Wiki</a>
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikiis_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><strong><%= current_user.username %></strong> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
              <li role="separator" class="divider"></li>
              <% if current_user.standard? %>
                <li><a href="/charges/new">Go Premium <span class="glyphicon glyphicon-flash"></span></a></li>
              <% else %>
                <li><a href="#">Private Wikis <span class="glyphicon glyphicon-sunglasses"></span></a></li>
              <% end %>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <body>
    <div class="container">
      <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
      <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
      <% end %>
      <%= yield %>

    </div>
  </body>

  <footer class="footer">
      <p>© 2018 | Wiki</p>
  </footer>
</html>

app/views/users/downgrade.html.erb
<h1>Users#downgrade</h1>
<p>Find me in app/views/users/downgrade.html.erb</p>

app/views/welcome/about.html.erb
<div class="jumbotron">
  <h1>About Us</h1>
  <h2>Four score and seven years ago...</h2>
  <p><br /></p>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <% if user_signed_in? %>
    <h1>Hi, <%= current_user.username %></h1>
    <h2>We're glad to have you back.</h2>
      <% if current_user.role == 'standard' %>
        <h3>Have you considered upgrading to a <a href='/charges/new'>premium user</a>?</h3>
      <% else %>
        <h3>Here are your private wikis:</h3>
        <p>index private wikis here</p>
      <% end %>
  <% else %>
    <h1>Welcome to Wiki</h1>
    <h2>Modern, minimal, sharable markdown wikis.</h2>
    <p><br /></p>
    <p><a class="btn btn-primary btn-lg sharp" href="/users/sign_up" role="button">Sign Up</a>  <a class="btn btn-info btn-lg sharp" href="/users/sign_in" role="button">Sign In</a></p>
  <% end %>
</div>

app/views/wikiis/_form.html.erb
<%= form_for [wikii] do |f| %>
  <% if wikii.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wikii.errors.count, "error") %>.</h4>
      <ul>
        <% wikii.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(wikii.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(wikii.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter content" %>
  <% end %>
  <% if current_user.premium? || current_user.admin? %>
    <%= form_group_tag(wikii.errors[:private]) do %>
      <%= f.label "Set Private" %>
      <%= f.check_box :private, class: 'form-control' %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikiis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <h3>Guidelines</h3>
      <ul>
        <li>Only truth.</li>
        <li>Share your wisdom.</li>
        <li>Connect the dots.</li>
      </ul>
    <h3>Collaborators</h3>
      <%= render partial: 'collaborators/form', locals: { wikii: @wikii } %>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wikii: @wikii } %>
  </div>
</div>

app/views/wikiis/index.html.erb
<div class="page-header">
  <h1>All Wikis
  </h1>
  <% if current_user %>
    <%= link_to "New Wiki", new_wikii_path(@wikii), class: 'btn btn-success' %>
  <% else %>
    <p><a href="/users/sign_up">Sign Up</a> or <a href="/users/sign_in">Sign In</a> to Create a Wiki</p>
  <% end %>
</div>
<div class="row">
  <div class="col-md-10">
    <% @wikiis.each do |wikii| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <% if wikii.private %>
              <span class="glyphicon glyphicon-sunglasses"></span> <%= link_to wikii.title, wikii %>
            <% else %>
              <%= link_to wikii.title, wikii %>
            <% end %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/wikiis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wikis</p>
    <ul>
      <li>Only truth.</li>
      <li>Share your wisdom.</li>
      <li>Connect the dots.</li>
    </ul>
  </div>
  <div class="col-md-8">

    <%= render partial: 'form', locals: { wikii: @wikii } %>
  </div>
</div>

app/views/wikiis/show.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-md-8">
      <% if @wikii.private? %>
      <h1><span class="glyphicon glyphicon-sunglasses"></span> <%= @wikii.title %></h1>
      <% else %>
      <h1><%= @wikii.title %></h1>
      <% end %>
      <small>Created <%= time_ago_in_words(@wikii.created_at) %> ago by <%= @wikii.user.username %>.</small>
    </div>

    <div class="col-md-4">
      <div class="pull-right">
        <% if current_user %>
          </br></br>
          <%= link_to "Edit", edit_wikii_path(@wikii), class: 'btn btn-success' %>
          <%= link_to "Delete", @wikii, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
        <% else %>
          </br></br></br>
          <small><a href="/users/sign_up">Sign Up</a> or <a href="/users/sign_in">Sign In</a> to edit a Wiki</small>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wikii.body) %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <p><%= render partial: 'collaborators/list' %></p>
  </div>
</div>